#spring.application.name=JournalApp
#spring.data.mongodb.uri=mongodb+srv://vikashmau950_db_user:7aO9yWdbsk58OEdT@cluster0.jot8ah4.mongodb.net/journaldb
#spring.data.mongodb.auto-index-creation=true
#server.port=8081
#server.servlet.context-path=/journal




#spring.main.allow-circular-references=true
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword


#This file is not use but I contain for informative purpose